name: Build VSCode extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # get npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Visual Studio Code Extension Manager
        run: npm install -g vsce

      - name: Install npm dependencies
        run: npm install
        working-directory: ./vscode-extension
  
      - name: Copy license file to make Visual Studio Code Extension Manager not cry
        run: cp LICENSE vscode-extension/LICENSE

      - name: Build package
        run: vsce package
        working-directory: ./vscode-extension

      - uses: actions/upload-artifact@v4
        with:
          name: adhoc-vscode-extension
          path: vscode-extension/adhoc-*.vsix
          if-no-files-found: error
